version: '3.7'

services:
  go-saudi-app:
    image: me-central1-docker.pkg.dev/heroic-footing-422415-n9/go-saudi-be/go-saudi-be:latest
    container_name: go-saudi-be
    ports:
      - "1337:1337"
    env_file:
      - .env
    volumes:
      - /home/ubuntu/backup:/usr/src/app/public/uploads
    restart: always
    networks:
      - go-saudi-network
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: '4G'
        reservations:
          cpus: '0.75'
          memory: '3G'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:1337/"]
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "50"

networks:
  go-saudi-network:
    driver: bridge

volumes:
  backup:
