version: '3.7'

services:
  go-saudi-app:
      image: me-central1-docker.pkg.dev/heroic-footing-422415-n9/go-saudi-be-staging/go-saudi-be:1
    container_name: go-saudi-be
    ports:
      - "1337:1337"
    env_file:
      - .env
    volumes:
      - /home/ubuntu/backup:/usr/src/app/public/uploads
    restart: always
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: '4G'
        reservations:
          cpus: '0.75'
          memory: '3G'

networks:
  go-saudi-network:
    driver: bridge

volumes:
  backup:
