version: '3.7'

services:
  go-saudi-app:
    image: me-central1-docker.pkg.dev/heroic-footing-422415-n9/go-saudi-be-staging/go-saudi-be-staging:latest
    container_name: go-saudi-be
    ports:
      - "1337:1337"
    env_file:
      - .env
    volumes:
      - /home/ubuntu/backup:/usr/src/app/public/uploads
    networks:
      - go-saudi-network
    depends_on:
      - mysql
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: '3G'
        reservations:
          cpus: '0.5'
          memory: '2G'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:1337/"]
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "50"

  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USERNAME}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - /home/ubuntu/mysql-data:/var/lib/mysql
    networks:
      - go-saudi-network
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: '0.5'      # MySQL allocated 0.5 vCPUs
          memory: '2G'     # MySQL allocated 2 GB memory
        reservations:
          cpus: '0.25'     # MySQL reserved 0.25 vCPUs
          memory: '1G'     # MySQL reserved 1 GB memory
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "50"

networks:
  go-saudi-network:
    driver: bridge

volumes:
  backup:
  mysql-data:
